### PR TITLE
Add authorization rules

### PR DESCRIPTION
**Pull request by mohamedgamaleldin999999**
This PR is trying to fulfill these requirements:

Install CanCanCan in your project.
Add a role column to the users table. Remember to use a migration for this.
A user can delete a post if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
For that you need to implement the post deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.
A user can delete a comment if it is theirs or if they have an admin role (column role has value "admin"). Use CanCanCan for this authorization.
For that you need to implement the comment deleting functionality. Add the "Delete" button to the view and make sure that only authorized users can see it.

### CODE REVIEW

**Comment by topeogunleye** [comment]
@mohamedgamaleldin999999 , @banzaman, please do me a strong one and fix your linter errors

**Comment by banzaman** [comment]
> @mohamedgamaleldin999999 , @banzaman, please do me a strong one and fix your linter errors

let's work on it

**Comment by topeogunleye** [comment]
> > @mohamedgamaleldin999999 , @banzaman, please do me a strong one and fix your linter errors
> 
> let's work on it

It's just a case of replacing double quotation marks with single quotation marks

**Review by topeogunleye — APPROVED** [review]
Hi @banzaman, @mohamedgamaleldin999999 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

dwayne-the-rock

## (Highlights) Good Points: 💪 
- You have successfully implemented the **CanCanCan** gem to handle authorization for posts and comments. 👏
- You have defined the **ability** class to specify the rules for different user roles. 👍
- You have created a **user.admin?** method in the user model to check if a user is an admin. This is a good practice to keep your code DRY and readable. 🙌
- You have used the **load_and_authorize_resource** method in the posts controller to authorize posts automatically. This is a convenient way to use CanCanCan. 🚀

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
